### ISSUE TITLE
AQI comparison to <insert something resembling a standard>

### ISSUE THREAD

**Issue by causalloop** [G6EJD/BME680-Example#4]
They should really have an extra tab for questions since this isn't actual an issue...

Despite there not being an ISO standard for the measurement of air quality, there seems to be _some_ metric by which <insert news organization/weather channel> says, "here's the index, the quality is somewhere between amazing and how are you still alive".  Have you compared your calculations to that of some somewhat reputable source of that source of information?  There's obviously no "right" answer here since no standard has been established, I'm just curious how this would stack up to what we get in the "news".

I'd do some comparisons of my own, but I've only got about 2 hours worth of data - well, more like 20 minutes since there's a 45 minutes span where my first foray into a DIY weather-station goes to sleep.  I can go into more detail about that, but didn't want to flood this with lots of 'god this guy writes too much' material 😁

**Comment by G6EJD** [comment]
It’s an interesting and yet confusing subject (AQI) because as you say most weather agencies report air quality but against it seems their own standards. This is where I got to, I knew that high humidity feels very uncomfortable as does a very dry atmosphere so that gave me the basis of the mix 0-40% for humidity and the rest gas concentrations. For gas Bosch give a indication that the range of very high to low concentrations is 5 to 50k of gas resistance based on the ratio of air to gas and clearly resistance is low when there is a lot of bad gases around.
Next came the de-facto scale of air quality used in some industries and so I scaled the combined result to that, essentially a 0 to 5 result.
Bosch have their own AQI but it’s not in the public domain and only available as an ESP8266 binary plus a few other platforms, what I haven’t done is compared my index with theirs as I could not get their binary to link in using the Arduino IDE.
I don’t understand Bosch doing that as it seems to limit sales and sensor take up, I’m sure there’s a good reason.
Comparison with weather/news Chanel indices - no none done I think without a reference it would be of no value. Incidentally, the index I produced could be augmented with temperature on the basis that if it’s too hot or cold then the air quality is poor, a three way index. Centre of temperature would probably be 21°C.

**Comment by causalloop** [comment]
I've heard the same about Bosch - I guess as long as we can pull something useful and consistent out of it, all that really matters is 'am I going to die if I walk outside' lol

Thanks for the clarification.  I shall now close this not a bug issue :)

**Comment by causalloop** [comment]
works for me!
