### ISSUE TITLE
BME680 Gives Much More Than 50kOhm

### ISSUE THREAD

**Issue by WhymustIhaveaname** [G6EJD/BME680-Example#9]
You said that the maximum output of bme680 gas resistance is 50 kOhm. However, my bme680 normally gives about 100kOhm, and sometimes even 150kOhm.

**Comment by G6EJD** [comment]
What is the code issue you are reporting?

Your not understanding the qualitative index correctly, any gas resistance Above 50K even up to 300K assumes clean air with No pollution caused by gas.

You should explain what your issue is not make statements.

Did you check the code to see that the maximum gas resistance can be 300K?

**Comment by WhymustIhaveaname** [comment]
Thanks, you have answered my question.
